export type ServiceStatus = "active" | "paused";
export type WalletType = "human" | "agent" | "provider";

/**
 * Shared wallet identity contract — canonical shape used across AgentPay and AgentMart.
 * AgentPay is the single source of truth; AgentMart reads/writes through AgentPay's API.
 */
export interface SharedWalletIdentity {
  address: string;
  type: WalletType;
  displayName: string;
  registeredAt: string; // ISO
}
export type UsageStatus = "success" | "failed" | "timeout";
export type AuthorizationStatus = "active" | "paused" | "revoked";

export interface Service {
  id: string;
  providerWallet: string;
  name: string;
  endpoint: string;
  pricePerCall: number; // integer micro-USDC
  platformFeeBps: number;
  description: string;
  category: string;
  status: ServiceStatus;
  totalCalls: number;
  grossVolume: number;
  totalEarned: number; // provider net earnings
  totalFees: number; // platform fees generated by this service
  createdAt: string; // ISO
}

export interface Wallet {
  address: string;
  type: WalletType;
  name: string;
  totalSpent: number;
  totalEarned: number;
  createdAt: string; // ISO
  lastActiveAt: string; // ISO
}

export interface UsageRecord {
  id: string;
  serviceId: string;
  callerWallet: string;
  providerWallet: string;
  grossAmount: number;
  platformFee: number;
  providerNet: number;
  status: UsageStatus;
  latencyMs: number;
  timestamp: string; // ISO
  txHash?: string; // on-chain settlement transaction hash (Base Sepolia)
}

export interface Authorization {
  callerWallet: string;
  serviceId: string;
  spendCap: number;
  spent: number;
  status: AuthorizationStatus;
  createdAt: string; // ISO
}

export interface PlatformStats {
  totalVolume: number;
  totalFees: number;
  totalCalls: number;
  totalServices: number;
  totalWallets: number;
}
